In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_excel("data/citizens_by_birth.xlsx")

In [3]:
df1 = df1.replace(r":.*", np.nan, regex=True)

In [4]:
df1 = df1.dropna()

In [5]:
df1.head()

Empty DataFrame
Columns: [LEV_PERC (Labels), Strong, Unnamed: 2, Intermediate, Unnamed: 4, Poor]
Index: []

In [6]:
df1["Poor"] = pd.to_numeric(df1["Poor"], errors="coerce")

In [7]:
df1 = df1.dropna(subset=["Poor"])

In [8]:
df1 = df1[~df1["Poor"].astype(str).str.contains("u")]

In [9]:
df1.head()

Empty DataFrame
Columns: [LEV_PERC (Labels), Strong, Unnamed: 2, Intermediate, Unnamed: 4, Poor]
Index: []

In [10]:
df2 = pd.read_excel("data/eu_migrants_2019.xlsx")

In [11]:
df2 = df2.replace(r":.*", np.nan, regex=True)

In [12]:
df2["Poor"] = pd.to_numeric(df2["Poor"], errors="coerce")

In [13]:
df2 = df2.dropna(subset=["Poor"])

In [14]:
df2 = df2[~df2["Poor"].astype(str).str.contains("u")]

In [15]:
df2.tail()

,LEV_PERC (Labels),Strong,Unnamed: 2,Intermediate,Unnamed: 4,Poor,Unnamed: 6
22,Austria,45.3,NaN,44.9,NaN,9.7,NaN
23,Ireland,40.8,NaN,51.6,NaN,7.6,NaN
24,Cyprus,50.3,NaN,42.7,NaN,7.1,NaN
25,Poland,40.3,NaN,53,NaN,6.7,NaN
26,Spain,44.5,NaN,49.4,NaN,6.1,NaN

In [16]:
df3 = pd.read_excel("data/non_eu_countries_2019.xlsx")

In [17]:
df3 = df3.replace(r":.*", np.nan, regex=True)

In [18]:
df3["Poor"] = pd.to_numeric(df3["Poor"], errors="coerce")

In [19]:
df3 = df3.dropna(subset=["Poor"])

In [20]:
df3 = df3[~df3["Poor"].astype(str).str.contains("u")]

In [21]:
df1 = pd.read_excel("data/citizens_by_birth.xlsx")
df2 = pd.read_excel("data/eu_migrants_2019.xlsx")
df3 = pd.read_excel("data/non_eu_countries_2019.xlsx")

df1["dataset"] = "Table 1"
df2["dataset"] = "Table 2"
df3["dataset"] = "Table 3"

df = pd.concat([df1, df2, df3])

In [22]:
df.head()

,LEV_PERC (Labels),Strong,Unnamed: 2,Intermediate,Unnamed: 4,Poor,dataset,Unnamed: 6
0,GEO (Labels),NaN,NaN,NaN,NaN,NaN,Table 1,NaN
1,Romania,17.3,NaN,57.9,NaN,24.9,Table 1,NaN
2,Greece,21.6,NaN,54.2,NaN,24.2,Table 1,NaN
3,Latvia,19.2,NaN,56.6,NaN,24.2,Table 1,NaN
4,Estonia,17.5,NaN,59.5,NaN,23,Table 1,NaN

In [23]:
df = df.rename(columns={"LEV_PERC (Labels)": "country"})

In [24]:
df.head()

,country,Strong,Unnamed: 2,Intermediate,Unnamed: 4,Poor,dataset,Unnamed: 6
0,GEO (Labels),NaN,NaN,NaN,NaN,NaN,Table 1,NaN
1,Romania,17.3,NaN,57.9,NaN,24.9,Table 1,NaN
2,Greece,21.6,NaN,54.2,NaN,24.2,Table 1,NaN
3,Latvia,19.2,NaN,56.6,NaN,24.2,Table 1,NaN
4,Estonia,17.5,NaN,59.5,NaN,23,Table 1,NaN

In [25]:
df = df.dropna(subset=["Poor"])

In [26]:
df.head()

   country Strong Unnamed: 2 Intermediate Unnamed: 4  Poor  dataset Unnamed: 6
1  Romania   17.3        NaN         57.9        NaN  24.9  Table 1        NaN
2   Greece   21.6        NaN         54.2        NaN  24.2  Table 1        NaN
3   Latvia   19.2        NaN         56.6        NaN  24.2  Table 1        NaN
4  Estonia   17.5        NaN         59.5        NaN    23  Table 1        NaN
5  Finland   22.6        NaN         55.3        NaN    22  Table 1        NaN

In [27]:
df= df.drop(['Unnamed: 2', 'Unnamed: 4','Unnamed: 6'], axis=1)

In [28]:
df.tail()

           country Strong Intermediate Poor  dataset
29         Romania      :            :    :  Table 3
30         Iceland      :            :    :  Table 3
31          Norway      :            :    :  Table 3
32  United Kingdom      :            :    :  Table 3
33         Türkiye      :            :    :  Table 3